var clickByText = require('../testAssets/clickByText')

module.exports = (pageObject, formInfo) => {
    pageObject
        .waitForElementVisible('@listProductLoggedIn', 5000)
        .click('@listProductLoggedIn')
        .click('@guideMe')
    pageObject
        .clearValue('@step1Title')
        .setValue('@step1Title', formInfo.title)
        .clearValue('@step1Description')
        .setValue('@step1Description', formInfo.description)
        .click('@step1CategorySelect')
        .click(`option[value="${formInfo.category}"]`)
        .click('@step1Next')
        // .click('step2UploadPhotos')
        // .setValue('@uploadPhoto', require('/users/madelinethomas/Documents/DevMtn/my-stuff/yoodlize-test-photos').resolve(__dirname + '/dog-backpack.jpg'))
        .click('@step2Next')
        .clearValue('@step3Address1')
        .setValue('@step3Address1', formInfo.address1)
        .clearValue('@step3Address2')
        .setValue('@step3Address2', formInfo.address2)
        .clearValue('@step3City')
        .setValue('@step3City', formInfo.city)
        .clearValue('@step3State')
        .setValue('@step3State', formInfo.state)
        .clearValue('@step3Zip')
        .setValue('@step3Zip', formInfo.zip)
        .click('@step3Next')
        .click('@step4Next')
        .clearValue('@step5Price')
        .setValue('@step5Price', formInfo.price)
        .click('@step5Next')
        .clearValue('@step6Rule')
        .setValue('@step6Rule', formInfo.rule)
        .click('@step6Add')
        .click('@step6Next')
        .waitForElementVisible('@previewListing', 1000)
        .click('@publishNow')
        .waitForElementVisible('@publishedDescription', 1000)
}