module.exports = {
    url: 'https://alpha.yoodlize.com/',
    elements: {
        // Home Page
        homePage: 'div[class="navbar-header"]',
        seeAllTools: 'div[data-reactid="84"]',
        objectSlider: 'div[class="slider sc-btzYZH lgYiAd sc-bwzfXH loXcNn sc-bdVaJa iHZvIS"]',
        item: 'div[data-reactid="92"]',
        itemName: 'div[class="sc-dNLxif hHahiq sc-gqjmRU koYdEt"]',
        seeAllTools: 'div[data-reactid="84"]',          
        seeAllToysGames: 'div[data-reactid="130"]',
        seeAllSportGoods: 'div[data-reactid="173"]',
        seeAllBusEquip: 'div[data-reactid="228"]',
        seeAllElectronics: 'div[data-reactid="271"]',
        seeAllHomeLawnGarden: 'div[data-reactid="319"]',
        seeAllFashion: 'div[data-reactid="366"]',
        seeAllOutdoorGear: 'div[data-reactid="414"]',
        seeAllExperiences: 'div[data-reactid="461"]',
        seeAllParty: 'div[data-reactid="505"]',
        seeAllProperties: 'div[data-reactid="549"]',
        seeAllRVs: 'div[data-reactid="588"]',
        // Home Page Circle Categories
        businessEquipment: 'div[data-reactid="629"]',
        electronics: 'div[data-reactid="634"]',
        recreationalVehicles: 'div[data-reactid="639"]',
        fashion: 'div[data-reactid="645"]',
        homeAndGarden: 'div[data-reactid="650"]',
        outdoorGear: 'div[data-reactid="655"]',
        partyEquipment: 'div[data-reactid="661"]',
        properties: 'div[data-reactid="666"]',
        experiences: 'div[data-reactid="671"]',
        sportingEquipment: 'div[data-reactid="677"]',
        tools: 'div[data-reactid="682"]',
        toysAndGames: 'div[data-reactid="687"]',
        // Search
        searchField: 'input[type="text"]',
        searchBtn: 'button[class="sc-kPVwWT bwXMGY sc-ifAKCX kzsifC"]',
        browse: 'a[href="/s"]',
        results: 'div[class="col-md-12 col-sm-12 col-xs-12"]',
         // Search Filters
         showMap: 'img[class="sc-qrIAp hAcQer"]',
         searchWithMap: 'ins[class="iCheck-helper"]',
         mapZoomIn: 'button[title="Zoom in"]',
         mapZoomOut: 'button[title="Zoom out"]',
         categories: '//button[text()="Categories"]',
         catBusinessEquipment: '//button[text()="Business Equipment"]',
         catExperiences: '//button[text()="Experiences"]',
         catHomeGarden: '//button[text()="Home and Garden"]',
         catPartyEquipment: '//button[text()="Party Equipment"]',
         catRVs: '//button[text()="Recreational Vehicles"]',
         catTools: '//button[text()="Tools"]',
         catElectronics: '//button[text()="Electronics"]',
         catFashion: '//button[text()="Fashion"]',
         catOutdoorGear: '//button[text()="Outdoor Gear"]',
         catProperties: '//button[text()="Properties"]',
         catSportingEquipment: '//button[text()="Sporting Equipment"]',
         catToysGames: '//button[text()="Toys and Games"]',
         dates: '//button[text()="Dates"]',
         dropOff: 'input[name="startDate"]',
         pickUp: 'input[name="endDate"]',
         applyButton: 'button[class="sc-hmXxxW knXwTd"]',
         price: '//button[text()="Price"]',
         minPrice: '(//input[@placeholder="Optional"])[1]',
         maxPrice: '(//input[@placeholder="Optional"])[2]',
         sort: '//button[text()="Sort"]',
         sortHighLow: '//button[text()="High - Low"]',
         sortLowHigh: '//button[text()="Low - High"]',
        /* oneStar: '',
         twoStars: '',
         threeStars: '',
         fourStars: '',
         fiveStars: '',
         firstItem: '',
        // List Products */
        listProduct: 'span[data-reactid="34"]',
        quideMe: '//button[text()="GUIDE ME"]',
        iGotIt: '//button[text()="I GOT IT!"]',
        // List an Item
        title: 'input[type="text"]',
        description: 'textarea[class="sc-gHboQg bQZZfx"]',
        fashionPick: '//option[text()="Fashion"]',
        businessEquipmentPick: '//option[text()="Business Equipment"]',
        recreationalVehiclesPick: '//option[text()="Recreational Vehicles"]',
        toolsPick: '//option[text()="Tools"]',
        electronicsPick: '//option[text()="Electronics"]',
        partyEquipmentPick: '//option[text()="Party Equipment"]',
        homeAndGardenPick: '//option[text()="Home and Garden"]',
        outdoorGearPick: '//option[text()="Outdoor Gear"]',
        sportingEquipmentPick: '//option[text()="Sporting Equipment"]',
        propertiesPick: '//option[text()="Properties"]',
        experiencesPick: '//option[text()="Experiences"]',
        toysAndGamesPick: '//option[text()="Toys and Games"]',
        nextBtn: 'button[class="sc-kPVwWT fqLuIb sc-ifAKCX kzsifC"]',
        streetAddress: 'input[name="street"]',
        city: 'input[name="city"]',
        state: 'input[name="state"]',
        zipcode: 'input[name="zipcode"]',
        dayPicker: 'div[class="DayPicker-Day"]',
        dailyRate: 'input[type="dailyRate"]',
        rules: 'input[class="_3wXqb',
        addBtn: '//button[text()="ADD"]',
        // Profile
        avatarIcon: 'a[role="button"]',
        dashboard: 'div[data-reactid="56"]',
        editProfile: 'div[data-reactid="60"]',
        accountSetting: 'div[data-reactid="64"]',
        logout: 'div[data-reactid="69"]',
        inbox: '//div[text()="Inbox"]',
        listing: '//div[text()="Listing"]',
        reviews: '//div[text()="Reviews"]',
        profile: '//div[text()="Profile"]',
        account: '//div[text()="Account"]',
        // Edit Profile
        firstName: 'input[name="firstName"]',
        lastName: 'input[name="lastName"]',
        gender: '//option[text()="Gender"]',
        malePick: '//option[text()="Male"]',
        femalePick: '//option[text()="Female"]',
        otherPick: '//option[text()="Other"]',
        month: '//option[text()="5"]',
        day: '//option[text()="30"]',
        year: '//option[text()="1985"]',
        emailAddress: 'input[name="email"]',
        language: '//option[text()="English"]',
        currency: '//option[text()="USD"]',
        location: 'input[name="location"]',
        describeY: 'textarea[name="info"]',
        // Item View Page
        firstItem: 'div[data-reactid="114"]',           
        itemTitle: 'div[class="sc-dNLxif hHahiq sc-gqjmRU koYdEt"]',
        itemImage: 'img[class="sc-gqPbQI lkKrpm"]',
        itemDescription: 'div[class="sc-bAeIUo TzWXY sc-dNLxif fdMhjG sc-gqjmRU iMgiCn"]',
        rentalRules: 'li[class="sc-hORach cfqFhl"]',
        ownerName: 'div[class="sc-dNLxif kLnwCQ sc-gqjmRU grDSVw"]',
        contactOwner: 'div[class="sc-dNLxif gXXneo sc-gqjmRU grDSVw"]',
        itemRate: 'div[class="sc-dNLxif iAGaBz sc-gqjmRU gbowmt',
        pickupDate: 'input[id="It is Start date id"]',
        dropoffDate: 'input[id="It is End date id"]',
        requestButton: 'button[class="sc-kPVwWT gnFPkq sc-ifAKCX kzsifC"]',
        favorite: 'div[class="sc-gojNiO cBrEyX"]',
        nearbyItems: 'div[class="sc-dNLxif OxNuC sc-gqjmRU dzDRCD"]',
        // Account
        accountSettings: 'a[href="/user/payout/"]',
        addPayout: 'a[href="/user/addpayout"]',
        country: 'select[name="country"]',
        selectUS: 'option[value="US"]',
        address1: 'input[name="address1"]',
        address2: 'input[name="address2"]',
        city: 'input[name="city"]',
        state: 'input[name="state"]',
        zipCode: 'input[name="zipcode"]',
        nextButton: 'span[data-reactid="138"]',
        payPalSelect: 'input[value="1"]',
        bankSelect: 'input[value="2"]',
        nextButton2: 'button[class="_1_L8P _2qtm_ _1PSHw btn btn-default"]',
        backButton: 'button[class="_1_L8P _1PSHw _1wYU2 uPEPu btn btn-default"]',
        payPalEmail: 'input[name="payEmail"]',
        selectCurrency: 'select[name="currency"]',
        selectUSD: 'option[value="USD"]',
        addPayout2: 'button[class="_1_L8P _1PSHw _2qtm_ btn btn-default"]',
        accountFirstName: 'input[name="firstname"]',
        accountLastName: 'input[name="lastname"]',
        routingNumber: 'input[name-"routingNumber"]',
        accountNumber: 'input[name="accountNumber"]',
        confirmAccountNumber: 'input[name="confirmAccountNumber"]',
        ssn4Digits: 'input[name="ssn4Digits"]',
        finishButton: 'button[class="_1_L8P _2qtm_ _1PSHw _2K7JB btn btn-default"]',
         // Request an Item
         pickupDate: 'input[id="It is Start date id"]',
         dropoffDate: 'input[id="It is End date id"]',
         requestButton: 'button[class="sc-kPVwWT gnFPkq sc-ifAKCX kzsifC"]',
         confirmThingsNext: 'button[class="_1IEeC _3Fc0g btn btn-default"]',
         uploadPhoto: 'input[class="dz-hidden-input"]',
         continueButton: 'button[class="_1_9c0 _26mrU btn btn-default"]',
         resendEmailButton: 'button[class="_25o3z _3n_Fi btn btn-default"]',
            // *** can't fill the rest until email verification is working ***
        // Sign Up

        // Login / Logout

        // Reviews

        // Messages / Inbox









    }
}